/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Project = {
  _id: string
  _type: "project"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug?: Slug
  summary?: string
  kind?: "paid" | "side" | "tool" | "takehome" | "coursework"
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  image: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  technologies: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "skill"
  }>
  keyTechnologies?: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "skill"
  }>
  githubUrl?: string
  liveUrl?: string
  liveLabel?: "View Site" | "View App"
  startDate?: string
  meta?: string
  highlight?: string
  metaLine?: string
  stats?: Array<{
    value?: string
    label?: string
    _key: string
  }>
  sections?: Array<{
    heading?: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }>
    _key: string
  }>
  screenshots?: Array<{
    caption?: string
    image?: {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    _key: string
  }>
}

export type Education = {
  _id: string
  _type: "education"
  _createdAt: string
  _updatedAt: string
  _rev: string
  degree: string
  institution: string
  period: string
  description?: string
  order: number
}

export type Experience = {
  _id: string
  _type: "experience"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  company: string
  period: string
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  order: number
}

export type Skill = {
  _id: string
  _type: "skill"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  kind: "technology" | "capability"
  detail?: string
  url?: string
  featured: boolean
  level?: "Beginner" | "Intermediate" | "Advanced" | "Expert"
  category:
    | "Languages"
    | "Mobile"
    | "Frontend"
    | "Backend"
    | "Ship & verify"
    | "Tools"
    | "Design"
    | "Other"
}

export type PersonalInfo = {
  _id: string
  _type: "personalInfo"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  role: string
  tagline?: string
  bio: string
  about?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  email: string
  phone?: string
  location?: string
  profileImage?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  socialLinks?: Array<{
    platform?:
      | "github"
      | "linkedin"
      | "twitter"
      | "instagram"
      | "facebook"
      | "youtube"
      | "other"
    url: string
    _key: string
  }>
}

export type Home = {
  _id: string
  _type: "home"
  _createdAt: string
  _updatedAt: string
  _rev: string
  featuredProjects?: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "project"
  }>
}

export type MediaTag = {
  _id: string
  _type: "media.tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Project
  | Education
  | Experience
  | Skill
  | PersonalInfo
  | Home
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: lib/queries.ts
// Variable: personalInfoQuery
// Query: *[_type == "personalInfo"][0] {    _id,    name,    role,    tagline,    bio,    about,    email,    phone,    location,    profileImage,    socialLinks[] {      platform,      url    }  }
export type PersonalInfoQueryResult = {
  _id: string
  name: string
  role: string
  tagline: string | null
  bio: string
  about: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }> | null
  email: string
  phone: string | null
  location: string | null
  profileImage: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  } | null
  socialLinks: Array<{
    platform:
      | "facebook"
      | "github"
      | "instagram"
      | "linkedin"
      | "other"
      | "twitter"
      | "youtube"
      | null
    url: string
  }> | null
} | null
// Variable: skillsQuery
// Query: *[_type == "skill"] {    _id,    name,    kind,    detail,    url,    featured,    category  }  | order(category asc, featured desc, name asc)
export type SkillsQueryResult = Array<{
  _id: string
  name: string
  kind: "capability" | "technology"
  detail: string | null
  url: string | null
  featured: boolean
  category:
    | "Backend"
    | "Design"
    | "Frontend"
    | "Languages"
    | "Mobile"
    | "Other"
    | "Ship & verify"
    | "Tools"
}>
// Variable: experiencesQuery
// Query: *[_type == "experience"] | order(order asc) {    _id,    title,    company,    period,    description,    order  }
export type ExperiencesQueryResult = Array<{
  _id: string
  title: string
  company: string
  period: string
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  order: number
}>
// Variable: educationQuery
// Query: *[_type == "education"] | order(order asc) {    _id,    degree,    institution,    period,    description,    order  }
export type EducationQueryResult = Array<{
  _id: string
  degree: string
  institution: string
  period: string
  description: string | null
  order: number
}>
// Variable: projectsQuery
// Query: *[_type == "project"] | order(startDate desc) {      _id,  title,  slug,  summary,  kind,  description,  image,  technologies[]->{    _id,    name,    category,    featured,    url  },  keyTechnologies[]->{    _id,    name,    category,    featured,    url  },  githubUrl,  liveUrl,  liveLabel,  meta,  highlight,  "hasDetail": count(sections) > 0  }
export type ProjectsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug | null
  summary: string | null
  kind: "coursework" | "paid" | "side" | "takehome" | "tool" | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }> | null
  image: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  technologies: Array<{
    _id: string
    name: string
    category:
      | "Backend"
      | "Design"
      | "Frontend"
      | "Languages"
      | "Mobile"
      | "Other"
      | "Ship & verify"
      | "Tools"
    featured: boolean
    url: string | null
  }>
  keyTechnologies: Array<{
    _id: string
    name: string
    category:
      | "Backend"
      | "Design"
      | "Frontend"
      | "Languages"
      | "Mobile"
      | "Other"
      | "Ship & verify"
      | "Tools"
    featured: boolean
    url: string | null
  }> | null
  githubUrl: string | null
  liveUrl: string | null
  liveLabel: "View App" | "View Site" | null
  meta: string | null
  highlight: string | null
  hasDetail: boolean | null
}>
// Variable: homeQuery
// Query: *[_type == "home"][0] {    featuredProjects[]->{        _id,  title,  slug,  summary,  kind,  description,  image,  technologies[]->{    _id,    name,    category,    featured,    url  },  keyTechnologies[]->{    _id,    name,    category,    featured,    url  },  githubUrl,  liveUrl,  liveLabel,  meta,  highlight,  "hasDetail": count(sections) > 0    }  }
export type HomeQueryResult = {
  featuredProjects: Array<{
    _id: string
    title: string
    slug: Slug | null
    summary: string | null
    kind: "coursework" | "paid" | "side" | "takehome" | "tool" | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
    image: {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
    }
    technologies: Array<{
      _id: string
      name: string
      category:
        | "Backend"
        | "Design"
        | "Frontend"
        | "Languages"
        | "Mobile"
        | "Other"
        | "Ship & verify"
        | "Tools"
      featured: boolean
      url: string | null
    }>
    keyTechnologies: Array<{
      _id: string
      name: string
      category:
        | "Backend"
        | "Design"
        | "Frontend"
        | "Languages"
        | "Mobile"
        | "Other"
        | "Ship & verify"
        | "Tools"
      featured: boolean
      url: string | null
    }> | null
    githubUrl: string | null
    liveUrl: string | null
    liveLabel: "View App" | "View Site" | null
    meta: string | null
    highlight: string | null
    hasDetail: boolean | null
  }> | null
} | null
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    image,    technologies[]->{      _id,      name,      category,      featured,      url    },    githubUrl,    liveUrl,    liveLabel,    metaLine,    stats[] { _key, value, label },    sections[] { _key, heading, body },    screenshots[] {      _key,      caption,      image,      "aspectRatio": image.asset->metadata.dimensions.aspectRatio    }  }
export type ProjectBySlugQueryResult = {
  _id: string
  title: string
  slug: string | null
  summary: string | null
  image: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  technologies: Array<{
    _id: string
    name: string
    category:
      | "Backend"
      | "Design"
      | "Frontend"
      | "Languages"
      | "Mobile"
      | "Other"
      | "Ship & verify"
      | "Tools"
    featured: boolean
    url: string | null
  }>
  githubUrl: string | null
  liveUrl: string | null
  liveLabel: "View App" | "View Site" | null
  metaLine: string | null
  stats: Array<{
    _key: string
    value: string | null
    label: string | null
  }> | null
  sections: Array<{
    _key: string
    heading: string | null
    body: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }> | null
  }> | null
  screenshots: Array<{
    _key: string
    caption: string | null
    image: {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    } | null
    aspectRatio: number | null
  }> | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "personalInfo"][0] {\n    _id,\n    name,\n    role,\n    tagline,\n    bio,\n    about,\n    email,\n    phone,\n    location,\n    profileImage,\n    socialLinks[] {\n      platform,\n      url\n    }\n  }\n': PersonalInfoQueryResult
    '\n  *[_type == "skill"] {\n    _id,\n    name,\n    kind,\n    detail,\n    url,\n    featured,\n    category\n  }\n  | order(category asc, featured desc, name asc)\n': SkillsQueryResult
    '\n  *[_type == "experience"] | order(order asc) {\n    _id,\n    title,\n    company,\n    period,\n    description,\n    order\n  }\n': ExperiencesQueryResult
    '\n  *[_type == "education"] | order(order asc) {\n    _id,\n    degree,\n    institution,\n    period,\n    description,\n    order\n  }\n': EducationQueryResult
    '\n  *[_type == "project"] | order(startDate desc) {\n    \n  _id,\n  title,\n  slug,\n  summary,\n  kind,\n  description,\n  image,\n  technologies[]->{\n    _id,\n    name,\n    category,\n    featured,\n    url\n  },\n  keyTechnologies[]->{\n    _id,\n    name,\n    category,\n    featured,\n    url\n  },\n  githubUrl,\n  liveUrl,\n  liveLabel,\n  meta,\n  highlight,\n  "hasDetail": count(sections) > 0\n\n  }\n': ProjectsQueryResult
    '\n  *[_type == "home"][0] {\n    featuredProjects[]->{\n      \n  _id,\n  title,\n  slug,\n  summary,\n  kind,\n  description,\n  image,\n  technologies[]->{\n    _id,\n    name,\n    category,\n    featured,\n    url\n  },\n  keyTechnologies[]->{\n    _id,\n    name,\n    category,\n    featured,\n    url\n  },\n  githubUrl,\n  liveUrl,\n  liveLabel,\n  meta,\n  highlight,\n  "hasDetail": count(sections) > 0\n\n    }\n  }\n': HomeQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    image,\n    technologies[]->{\n      _id,\n      name,\n      category,\n      featured,\n      url\n    },\n    githubUrl,\n    liveUrl,\n    liveLabel,\n    metaLine,\n    stats[] { _key, value, label },\n    sections[] { _key, heading, body },\n    screenshots[] {\n      _key,\n      caption,\n      image,\n      "aspectRatio": image.asset->metadata.dimensions.aspectRatio\n    }\n  }\n': ProjectBySlugQueryResult
  }
}
